### ISSUE TITLE
Good boy crashed

### ISSUE THREAD

**Issue by rllola** [BitcoinAmiens/dogecoin-tipping-bot#1]
Logs 
```
/usr/src/app/node_modules/blockcypher/lib/bcypher.js:395
		cb(error, body);
		^

TypeError: cb is not a function
    at /usr/src/app/node_modules/blockcypher/lib/bcypher.js:395:3
    at Request._callback (/usr/src/app/node_modules/blockcypher/lib/bcypher.js:71:4)
    at Request.self.callback (/usr/src/app/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
```

**Comment by rllola** [comment]
New version doesn't rely on bcypher anymore.
